{{- if and .Values.externalSecret.enabled .Values.redis.auth.enabled }}
apiVersion: {{ .Values.externalSecret.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "msp-demo.redisSecretName" . }}
  labels:
    {{- include "msp-demo.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "msp-demo.redisSecretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.redis.auth.passwordKey }}
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key | quote }}
        property: {{ .Values.externalSecret.remoteRef.property | quote }}
{{- end }}