{{- if and .Values.podDisruptionBudget.enabled (gt (int .Values.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "msp-demo.fullname" . }}
  labels:
    {{- include "msp-demo.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "msp-demo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
{{- end }}
